## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [43]:
arr = np.random.randint(10, size=10)
print(arr)
b = np.where(np.logical_or(arr > 8, arr < 3), arr, -arr)
print(b)

[8 9 0 6 5 1 2 4 9 6]
[-8  9  0 -6 -5  1  2 -4  9 -6]


**2.** Заменить максимальный элемент случайного массива на 0

In [243]:
arr[np.where(arr == np.max(arr))] = 0
print(arr)

[8 0 0 6 5 1 2 4 0 6]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [341]:
arr2 = np.random.randint(5, size=(2, 5))
print(arr2)
np.transpose([np.tile(arr2[0], len(arr2[1])), np.repeat(arr2[1], len(arr2[0]))])

[[1 3 0 2 1]
 [0 3 1 1 4]]


array([[1, 0],
       [3, 0],
       [0, 0],
       [2, 0],
       [1, 0],
       [1, 3],
       [3, 3],
       [0, 3],
       [2, 3],
       [1, 3],
       [1, 1],
       [3, 1],
       [0, 1],
       [2, 1],
       [1, 1],
       [1, 1],
       [3, 1],
       [0, 1],
       [2, 1],
       [1, 1],
       [1, 4],
       [3, 4],
       [0, 4],
       [2, 4],
       [1, 4]])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [250]:
A = np.random.randint(5, size=(8, 3))
B = np.random.randint(5, size=(2, 2))

filter_arr = []
for x in A:
    filter_arr.append(np.isin(B[0], x).any() & np.isin(B[1], x).any())

print(B)
print('//////')
print(A[filter_arr])

[[3 0]
 [2 2]]
//////
[[3 0 2]
 [3 2 1]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [234]:
arr3 = np.random.randint(2, size=(10, 3))

filter_array = []
for i in arr3:
    filter_array.append(not np.all(i == i[0]))

final_array = arr3[filter_array]
print(final_array)

[[0 1 0]
 [0 1 1]
 [1 1 0]
 [0 1 1]
 [0 0 1]
 [1 0 0]
 [1 1 0]
 [0 1 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [299]:
arr6 = np.random.randint(2, size=(5, 3))
print(arr6)
print('//////////')
arr6 = np.unique(arr6, axis=0)
print(arr6)

[[0 0 1]
 [0 0 1]
 [0 1 1]
 [1 0 1]
 [1 0 0]]
//////////
[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]]


Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

In [297]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, -3], [4, 4, 4]])
diag_x = np.diag(X)
np.prod(diag_x, axis=0, where = diag_x != 0, keepdims=True)[0]

-3

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [294]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
x.shape == y.shape and np.array_equal(np.sort(x), np.sort(y))

True

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль.
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [438]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
index = x==0
x[1:][index[:-1]].max()

[False False  True False  True  True False False  True]


array([False, False,  True, False,  True,  True, False, False])

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [316]:
x = np.array([2, 2, 2, 3, 3, 3, 5])
indexes = np.unique(x, return_index=True)[1]
indexes2 = np.append(indexes, len(x))
print([x[index] for index in sorted(indexes)])
print(indexes2[1:] - indexes)

[2, 3, 5]
[3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [382]:
import operator
import time
from scipy.spatial import distance
coords = [(35.0456, -85.2672),
          (35.1174, -89.9711),
          (35.9728, -83.9422),
          (36.1667, -86.7833)]

st = time.time()
print(distance.cdist(coords, coords, 'euclidean'))
print('Time for built-in function', (st - time.time()) * 100000000)

st = time.time()
empt = np.empty([len(coords), len(coords)])
for i in range(0, len(coords)):
    for j in range(0, len(coords)):
        empt[i][j] = np.linalg.norm(tuple(map(operator.sub, coords[i], coords[j])))
print(empt)
print('Time for my function: ' , (st - time.time()) * 100000000)


[[0.         4.70444794 1.6171966  1.88558331]
 [4.70444794 0.         6.0892811  3.35605413]
 [1.6171966  6.0892811  0.         2.84770898]
 [1.88558331 3.35605413 2.84770898 0.        ]]
Time for built-in function 0.0
[[0.         4.70444794 1.6171966  1.88558331]
 [4.70444794 0.         6.0892811  3.35605413]
 [1.6171966  6.0892811  0.         2.84770898]
 [1.88558331 3.35605413 2.84770898 0.        ]]
Time for my function:  0.0


* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [383]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [385]:
average_calories = np.average(calorie_stats)
average_calories

106.88311688311688

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [387]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [389]:
median_calories = np.median(calorie_stats_sorted)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [431]:
print(np.percentile(calorie_stats_sorted, 1))
print(np.percentile(calorie_stats_sorted, 1.5))
print(np.percentile(calorie_stats_sorted, 2))
print(np.percentile(calorie_stats_sorted, 3))
nth_percentile = np.percentile(calorie_stats_sorted, 3.3)
nth_percentile

50.0
50.0
50.0
55.599999999999994


60.16

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [425]:
more_calories = 1 - np.count_nonzero(calorie_stats_sorted < 60) / len(calorie_stats_sorted)
more_calories

0.961038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [428]:
np.std(calorie_stats_sorted)

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
Можно использовать процент хлопьев, в которых содержится более 60 калорий, чтобы показать, что CrunchieMunchies отлично подходят для людей на диете. А стандартное отклонение намного меньше, чем среднее значение, что показывает, что CrunchieMunchies один из немногих малокалорийных хлопьев на рынке.